<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3cf1a262e6d69496ec1a574c1f8bd26c
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twig\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3cf1a262e6d69496ec1a574c1f8bd26c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3cf1a262e6d69496ec1a574c1f8bd26c::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit3cf1a262e6d69496ec1a574c1f8bd26c::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
